flowchart TD
  F00000003445["Weicht die Ausgabestelle von der Ansch"] -->|"= ? → show"| G00000002211["Sitz der Ausgabestelle"]
  F00000003445["Weicht die Ausgabestelle von der Ansch"] -.->|"= ? → hide"| G00000002211["Sitz der Ausgabestelle"]